### ISSUE TITLE
!next broke pica once when there was one song

### ISSUE THREAD

**Issue by aaronshappell** [aaronshappell/picabot#43]
It will replay the song once and then pica stops responding to anything. I'll check the logs as soon as I can.

**Comment by aaronshappell** [comment]
Also shuffle was not on.

**Comment by aaronshappell** [comment]
Currently hasn't been recreated yet @dylan-thinnes

**Comment by aaronshappell** [comment]
Changing the priority to low unless it happens again and can be recreated.

**Comment by dylan-thinnes** [comment]
Hasn't happened again since, I think we're better off closing this for now and reopening it later.
